### PR TITLE
Modified hardcoded tests paths so that tests can be run whatever cwd is

### PR DESCRIPTION
**Pull request by euri10**
replaces #87 which I could not update properly

### CODE REVIEW

**Comment by euri10** [comment]
greetings @kushaldas , I rebased this little PR, not sure why circle CI doesnt kick in but in other projects I'm involved with, CI needs to be sometimes manually authorized by maintainers for PR from outside people, that might be the reason.

**Comment by kushaldas** [comment]
```The base branch requires all commits to be signed. [Learn more about signing commits.](https://docs.github.com/articles/about-gpg/)``` I guess this is why. @euri10 Can you please squash into 1 commit and sign that one?

**Comment by euri10** [comment]
> `The base branch requires all commits to be signed. [Learn more about signing commits.](https://docs.github.com/articles/about-gpg/)` I guess this is why. @euri10 Can you please squash into 1 commit and sign that one?

done, and the CI still doesn't start :)

**Comment by euri10** [comment]
there might be something in the circle CI config that prevents automated checks, see https://circleci.com/docs/enable-checks#troubleshooting-github-checks-waiting-for-status-in-github @kushaldas

**Comment by kushaldas** [comment]
I deleted the whole flow and added again, now it seems to be working. Not sure what was the issue.

**Comment by kushaldas** [comment]
Added one more commit to reformat using `black`.

**Review by kushaldas — APPROVED** [review]
All looks good. Thank you :)

**Comment by euri10** [comment]
thanks , will then follow up on others small tests PR :)

**Pull request merged**
